### ISSUE TITLE
options.searchText?

### ISSUE THREAD

**Issue by yiyizhai** [vazco/meteor-universe-autoform-select-demo#2]
Hi! I'm going through the demo. But I'm confused about `options.searchText`, `options.values`, and `options.params` in `getOptions` method. Where are they from? Thanks a lot

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
